name: gluco_coach
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.3
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  modal_progress_hud_nsn: ^0.5.1
  loading_animation_widget: ^1.0.0
  flutter_markdown: ^0.7.6+1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  cloud_firestore: ^5.6.3
  fl_chart: ^0.70.2
  url_launcher: ^6.1.10
  fluttertoast: ^8.2.8
  shared_preferences: ^2.3.0
  http: ^1.2.0
  numberpicker: ^2.1.2
  logger: ^2.4.0
  pdf: ^3.10.8
  path_provider: ^2.1.4
  open_file: ^3.3.2
  share_plus: ^10.0.2
  permission_handler: ^11.3.1
  shimmer: ^3.0.0


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.jpg" # Update with your actual icon path
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/

