// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv1P7Tci8q1SF1QhA6yvjPFqXDPSVEuwo',
    appId: '1:347924649881:web:cb980d8aac9164dcbee508',
    messagingSenderId: '347924649881',
    projectId: 'gluco-coach',
    authDomain: 'gluco-coach.firebaseapp.com',
    storageBucket: 'gluco-coach.firebasestorage.app',
    measurementId: 'G-L6PGDPK07J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRodZawuuWWqCMYuQjqM0sEpHq_ukY3SY',
    appId: '1:347924649881:android:8776e228b21b1c1dbee508',
    messagingSenderId: '347924649881',
    projectId: 'gluco-coach',
    storageBucket: 'gluco-coach.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjzbQdHdmxOQQ1U158O-30Xv1Brq9fEv8',
    appId: '1:347924649881:ios:af0243a58eb67c13bee508',
    messagingSenderId: '347924649881',
    projectId: 'gluco-coach',
    storageBucket: 'gluco-coach.firebasestorage.app',
    iosBundleId: 'com.example.glucoCoach',
  );
}
